;; alternate approach (let ((default-directory "~/.emacs.d/")) (shell-command "ls"))
(defun myshell ()
  (interactive)
  (mk-a-shell "*vmm*" "~/projects/vmm/")
  (mk-a-shell "*r12*" "~/projects/r12/")
  (mk-a-shell "*att*" "~/projects/att/")
  (mk-a-shell "*debug-helper*" "~/projects/att/")
  (mk-a-shell "*gitbook*" "/Users/cmagid/projects/rbm_geek_guides")
  )

(defun mk-a-shell (she-name dir-name)
  (setq tempy-buffy "*foooooo*")
  (switch-to-buffer tempy-buffy)
  (cd dir-name)
  (setq command-line-default-directory dir-name)
  (shell she-name)
  (switch-to-buffer tempy-buffy)
  (kill-buffer tempy-buffy)
  )

;;(myshell)
